providers = ["python"]

[phases.setup]
nixPkgs = ["uv"]

[phases.install]
cmds = ["uv sync --frozen"]

[phases.build]
cmds = ["true"]

[start]
cmd = "uv run --frozen uvicorn backend.app:app --host 0.0.0.0 --port $PORT"
