[phases.setup]
nixPkgs = ["python310"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  "/opt/venv/bin/pip install -r backend/requirements.txt"
]

[start]
cmd = "cd backend && /opt/venv/bin/uvicorn app:app --host 0.0.0.0 --port $PORT"
